# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bound_pointclouds.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import rospy
from marker_publisher import MarkerPublisher
from point_cloud_subscriber import PointCloudSubscriber

from PyQt5 import QtCore, QtGui, QtWidgets

import numpy as np

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.filename = 'pointcloud_xyzrgba.txt'
        self.bounding_box_publisher = MarkerPublisher(topic = 'bounding_box',type = 1,id = 6,color = 'r',scale = 0.05)
        self.point_cloud_subscriber_class = PointCloudSubscriber(topic = 'Obstacle_pointcloud')

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 876)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.x_label = QtWidgets.QLabel(self.centralwidget)
        self.x_label.setGeometry(QtCore.QRect(150, 90, 91, 41))
        self.x_label.setObjectName("x_label")
        self.y_label = QtWidgets.QLabel(self.centralwidget)
        self.y_label.setGeometry(QtCore.QRect(470, 90, 91, 41))
        self.y_label.setObjectName("y_label")
        self.z_label = QtWidgets.QLabel(self.centralwidget)
        self.z_label.setGeometry(QtCore.QRect(800, 90, 91, 41))
        self.z_label.setObjectName("z_label")
        self.y_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.y_label_3.setGeometry(QtCore.QRect(470, 410, 91, 41))
        self.y_label_3.setObjectName("y_length_label")
        self.z_length_label = QtWidgets.QLabel(self.centralwidget)
        self.z_length_label.setGeometry(QtCore.QRect(800, 410, 91, 41))
        self.z_length_label.setObjectName("z_length_label")
        self.x_length_label = QtWidgets.QLabel(self.centralwidget)
        self.x_length_label.setGeometry(QtCore.QRect(150, 410, 91, 41))
        self.x_length_label.setObjectName("x_length_label")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 20, 141, 51))
        self.label.setObjectName("label")


        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 740, 121, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.store_bounding_box)


        self.x_Slider = QtWidgets.QSlider(self.centralwidget)
        self.x_Slider.setGeometry(QtCore.QRect(150, 170, 51, 201))
        self.x_Slider.setMaximum(99)
        self.x_Slider.setProperty("value", 50)
        self.x_Slider.setOrientation(QtCore.Qt.Vertical)
        self.x_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.x_Slider.setTickInterval(10)
        self.x_Slider.setObjectName("x_Slider")
        self.x_Slider.valueChanged.connect(self.slider_value_changed)

        self.y_Slider = QtWidgets.QSlider(self.centralwidget)
        self.y_Slider.setGeometry(QtCore.QRect(460, 170, 51, 201))
        self.y_Slider.setMaximum(99)
        self.y_Slider.setProperty("value", 50)
        self.y_Slider.setOrientation(QtCore.Qt.Vertical)
        self.y_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.y_Slider.setObjectName("y_Slider")
        self.y_Slider.valueChanged.connect(self.slider_value_changed)

        self.z_Slider = QtWidgets.QSlider(self.centralwidget)
        self.z_Slider.setGeometry(QtCore.QRect(790, 170, 51, 201))
        self.z_Slider.setMaximum(99)
        self.z_Slider.setProperty("value", 50)
        self.z_Slider.setOrientation(QtCore.Qt.Vertical)
        self.z_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.z_Slider.setObjectName("z_Slider")
        self.z_Slider.valueChanged.connect(self.slider_value_changed)

        self.x_length_Slider = QtWidgets.QSlider(self.centralwidget)
        self.x_length_Slider.setGeometry(QtCore.QRect(150, 480, 51, 201))
        self.x_length_Slider.setOrientation(QtCore.Qt.Vertical)
        self.x_length_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.x_length_Slider.setObjectName("x_length_Slider")
        self.x_length_Slider.valueChanged.connect(self.slider_value_changed)

        self.y_length_Slider = QtWidgets.QSlider(self.centralwidget)
        self.y_length_Slider.setGeometry(QtCore.QRect(470, 480, 51, 201))
        self.y_length_Slider.setOrientation(QtCore.Qt.Vertical)
        self.y_length_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.y_length_Slider.setObjectName("y_length_Slider")
        self.y_length_Slider.valueChanged.connect(self.slider_value_changed)

        self.z_length_Slider = QtWidgets.QSlider(self.centralwidget)
        self.z_length_Slider.setGeometry(QtCore.QRect(790, 470, 51, 201))
        self.z_length_Slider.setOrientation(QtCore.Qt.Vertical)
        self.z_length_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.z_length_Slider.setObjectName("z_length_Slider")
        self.z_length_Slider.valueChanged.connect(self.slider_value_changed)


        self.x_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x_label_2.setGeometry(QtCore.QRect(220, 340, 91, 41))
        self.x_label_2.setObjectName("x_label_2")
        self.x_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.x_label_3.setGeometry(QtCore.QRect(220, 160, 91, 41))
        self.x_label_3.setObjectName("x_label_3")
        self.x_label_4 = QtWidgets.QLabel(self.centralwidget)
        self.x_label_4.setGeometry(QtCore.QRect(530, 340, 91, 41))
        self.x_label_4.setObjectName("x_label_4")
        self.x_label_5 = QtWidgets.QLabel(self.centralwidget)
        self.x_label_5.setGeometry(QtCore.QRect(530, 160, 91, 41))
        self.x_label_5.setObjectName("x_label_5")
        self.x_label_6 = QtWidgets.QLabel(self.centralwidget)
        self.x_label_6.setGeometry(QtCore.QRect(860, 340, 91, 41))
        self.x_label_6.setObjectName("x_label_6")
        self.x_label_7 = QtWidgets.QLabel(self.centralwidget)
        self.x_label_7.setGeometry(QtCore.QRect(860, 160, 91, 41))
        self.x_label_7.setObjectName("x_label_7")
        self.x_label_8 = QtWidgets.QLabel(self.centralwidget)
        self.x_label_8.setGeometry(QtCore.QRect(210, 650, 91, 41))
        self.x_label_8.setObjectName("x_label_8")
        self.x_label_9 = QtWidgets.QLabel(self.centralwidget)
        self.x_label_9.setGeometry(QtCore.QRect(210, 470, 91, 41))
        self.x_label_9.setObjectName("x_label_9")
        self.x_label_10 = QtWidgets.QLabel(self.centralwidget)
        self.x_label_10.setGeometry(QtCore.QRect(530, 650, 91, 41))
        self.x_label_10.setObjectName("x_label_10")
        self.x_label_11 = QtWidgets.QLabel(self.centralwidget)
        self.x_label_11.setGeometry(QtCore.QRect(530, 470, 91, 41))
        self.x_label_11.setObjectName("x_label_11")
        self.x_label_12 = QtWidgets.QLabel(self.centralwidget)
        self.x_label_12.setGeometry(QtCore.QRect(850, 640, 91, 41))
        self.x_label_12.setObjectName("x_label_12")
        self.x_label_13 = QtWidgets.QLabel(self.centralwidget)
        self.x_label_13.setGeometry(QtCore.QRect(850, 460, 91, 41))
        self.x_label_13.setObjectName("x_label_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1011, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.x_label.setText(_translate("MainWindow", "X (m)"))
        self.y_label.setText(_translate("MainWindow", "Y (m)"))
        self.z_label.setText(_translate("MainWindow", "Z (m)"))
        self.y_label_3.setText(_translate("MainWindow", "Y length (m)"))
        self.z_length_label.setText(_translate("MainWindow", "Z length (m)"))
        self.x_length_label.setText(_translate("MainWindow", "X length (m)"))
        self.label.setText(_translate("MainWindow", "Bound Pointclouds"))
        self.pushButton.setText(_translate("MainWindow", "Store PointCloud"))
        self.x_label_2.setText(_translate("MainWindow", "-1"))
        self.x_label_3.setText(_translate("MainWindow", "1"))
        self.x_label_4.setText(_translate("MainWindow", "-1"))
        self.x_label_5.setText(_translate("MainWindow", "1"))
        self.x_label_6.setText(_translate("MainWindow", "-1"))
        self.x_label_7.setText(_translate("MainWindow", "1"))
        self.x_label_8.setText(_translate("MainWindow", "0"))
        self.x_label_9.setText(_translate("MainWindow", "1"))
        self.x_label_10.setText(_translate("MainWindow", "0"))
        self.x_label_11.setText(_translate("MainWindow", "1"))
        self.x_label_12.setText(_translate("MainWindow", "0"))
        self.x_label_13.setText(_translate("MainWindow", "1"))

    def slider_value_changed(self):
        x,y,z,x_length,y_length,z_length = self.get_bounding_box_params()


        print("slider values:")
        print("x = %f, y = %f, z = %f"%(x,y,z))
        print("x_length = %f, y_length %f, z_length = %f"%(x_length,y_length,z_length))

        bounding_box = self.generate_bounding_box_pts(x,y,z,x_length,y_length,z_length)
        self.bounding_box_publisher.publish(bounding_box)

    def generate_bounding_box_pts(self,x,y,z,x_length,y_length,z_length):

        pt_0 = [           x,           y,           z]
        pt_1 = [           x,y + y_length,           z]
        pt_2 = [x + x_length,y + y_length,           z]
        pt_3 = [x + x_length,           y,           z]
        pt_4 = [           x,           y,z + z_length]
        pt_5 = [           x,y + y_length,z + z_length]
        pt_6 = [x + x_length,y + y_length,z + z_length]
        pt_7 = [x + x_length,           y,z + z_length]

        bounding_box = [pt_0,pt_1,pt_2,pt_3,pt_0,pt_4,pt_5,pt_6,pt_7,pt_4,pt_7,pt_3,pt_2,pt_6,pt_5,pt_1]

        return bounding_box

    def get_bounding_box_params(self):
        step_size_xyz = 0.02
        step_size_length = 0.01
        x = (self.x_Slider.value() - 50) * step_size_xyz
        y = (self.y_Slider.value() - 50) * step_size_xyz
        z = (self.z_Slider.value() - 50) * step_size_xyz
        x_length = self.x_length_Slider.value() * step_size_length
        y_length = self.y_length_Slider.value() * step_size_length
        z_length = self.z_length_Slider.value() * step_size_length
        return x,y,z,x_length,y_length,z_length


    def store_bounding_box(self):
        x,y,z,x_length,y_length,z_length = self.get_bounding_box_params()


        
        pcl_list = self.point_cloud_subscriber_class.get_pointcloud_with_color(x, x + x_length, y, y + y_length, z, z + z_length)
        np.savetxt(self.filename,np.array(pcl_list))

        print("bounding box stored, file name: %s"%(self.filename))


if __name__ == "__main__":
    rospy.init_node('BoundingBox_Publisher', anonymous=True)
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
